### ISSUE TITLE
TestAdapterPath should work together with other lookup methods

### ISSUE THREAD

**Issue by NikolayPianikov** [Microsoft/vstest-docs#103]
I mean project output directory, nuget and etc.

- We could have the identical behavior for full and core .net, I mean when I specify `TestAdapterPath` for .net full it does not try to find adapters in the project output directory but for .net core it properly finds.

So I should copy my custom adapter to the root of solution directory to run tests for mixed solution (with full .net and core .net projects). And vstest could spend potentially significant time finding all required adapters when agent checkout directory has a lot of files/directories. It is very important for CI.

- It would be great if we could specify several paths separated by semicolon or add new parameter `TestAdapterPaths` for that to work together with other lookup methods.

**Comment by smadala** [comment]
@NikolayPianikov
>It would be great if we could specify several paths separated by semicolon or add new parameter TestAdapterPaths for that to work together with other lookup methods.
You can use `/TestAdapterPath` argument multiple times [code](https://github.com/Microsoft/vstest/blob/master/src/vstest.console/Processors/TestAdapterPathArgumentProcessor.cs#L85).

**Comment by NikolayPianikov** [comment]
@smadala yes, but I used it under `dotnet test` or `msbuild /t:vstest`

**Comment by dtretyakov** [comment]
@smadala, in `VSTestTask`, which is shipped with .net core sdk, allowed only one argument for `VSTestTestAdapterPath` and it's is bypassed into vstest console as a [single argument](https://github.com/Microsoft/vstest/blob/123adc3ebfdc05be24ee6f44ace1e9eef79e372f/src/Microsoft.TestPlatform.Build/Tasks/VSTestTask.cs#L144):

And it's blocking use case in our integration, see https://github.com/JetBrains/teamcity-dotnet-plugin/issues/101

When do you plan to fix it?

**Comment by smadala** [comment]
This issue was moved to Microsoft/vstest#1319
