### ISSUE TITLE
How to access test results from data collector attachment

### ISSUE THREAD

**Issue by shenhong1000** [microsoft/vstest-docs#183]
[Data collector doc](https://github.com/Microsoft/vstest-docs/blob/master/docs/analyze.md) mention we can access test results from attachment. I still have no clue how to access it? Can you give an example?

**Comment by zmhh** [comment]
The dotnet test command output should say "Attachments:" and list the file(s) which were generated. The test coverage results are one or more of those files.

**Comment by aggarwalpulkit** [comment]
I have the exact same question. I don't see attachments or a way to get test result in datacollector. Any help is much appreciated.

**Comment by shenhong1000** [comment]
I find a way to access result from logger extension. You need implement ITestLoggerWithParameters and process it from TestResultHandler

https://github.com/microsoft/vstest-docs/blob/master/docs/report.md
https://github.com/microsoft/vstest/blob/master/src/Microsoft.TestPlatform.Extensions.TrxLogger/TrxLogger.cs

**Comment by aggarwalpulkit** [comment]
@shenhong1000 yes, I am using that in my implementation, however that is on the logger and not data collector. They are different beasts in my opinion.
