### ISSUE TITLE
Microsoft.TestPlatform.TranslationLayer NuGet package is not publicly available

### ISSUE THREAD

**Issue by mrward** [Microsoft/vstest-docs#19]
A Microsoft.TestPlatform.TranslationLayer NuGet package is mentioned in the documentation and I can see a few links to a MyGet package source in releases.md such as:

https://dotnet.myget.org/feed/vstest/package/nuget/Microsoft.TestPlatform.TranslationLayer/15.0.0-preview-20170106-08

However it looks like this MyGet feed is private. I had a look on a few other NuGet package sources but could not find the TranslationLayer NuGet package. 

Will the Microsoft.TestPlatform.TranslationLayer NuGet package be published somewhere so it is publicly available?

**Comment by codito** [comment]
@mrward the feed is public now. Please try [https://dotnet.myget.org/F/vstest/api/v3/index.json](https://dotnet.myget.org/F/vstest/api/v3/index.json). A sample application is [here](https://github.com/Microsoft/vstest/tree/master/samples/Microsoft.TestPlatform.TranslationLayer.E2ETest)

We'll publish the translation layer package on nuget.org in next few weeks.
