### ISSUE TITLE
SDK compatibility lists a version of VS that doesn't exist

### ISSUE THREAD

**Issue by jerhon** [Microsoft/vstest-docs#20]
I'm interested in the SDK to extend the testing framework.  However, in this section in the documentation for the SDK that lists compatibility it refers to a version of visual studio that doesn't exist.

In the "Test Platform SDK" document

Compatibility

Version	Compatibility
11.0.0	Supports VS 2012 - present
15.0.0	Supports VS 2016 - present

I'm confused, what is VS 2016?  Do you mean VS 2015 with some updates that were released in 2016 or VS 2017?   Could you please clarify this in the documentation?  

Thanks.

**Comment by codito** [comment]
@jerhon sorry, that's a typo. 15.x supports VS 2017 releases. Updated the doc. Please try it out and let us know if you have any feedback.
