### ISSUE TITLE
Can not build and run a local server follow Readme.md docs

### ISSUE THREAD

**Issue by yiyanwannian** [Microsoft/vstest-docs#42]
Hi 
     I can not run a local server follow Readme.md docs when I follow the steps to below:
 Editing docs

We use docfx for building this documentation. A short primer on editing this repo is below. First, download latest release of docfx and extract it locally. We will use d:\tmp\docfx as destination for these steps.   Open a command prompt, git clone this repo. Use the following commands to build and run a local server.

  > cd d:\src\vstest-docs
  > d:\tmp\docfx\docfx.exe build
  > d:\tmp\docfx\docfx.exe serve
Open http://localhost:8080/_site in a browser to see the rendering of the documentation.

    I can not find "docfx.exe" in my local File Explorer after latest docfx downloaded and the repo git clone finished.
   Am I missed some settings or your docs it not clearly ?
   below is my local File Explorer screenshot:
![downloadedfiles](https://cloud.githubusercontent.com/assets/8225547/24130948/98a4cdf0-0e26-11e7-8e31-bf95965ce229.png)
![searchdocfx exe](https://cloud.githubusercontent.com/assets/8225547/24130949/990db9e6-0e26-11e7-8179-dafdd4b1ab28.png)

Thanks
Houfa

**Comment by yiyanwannian** [comment]
Can not build and run a local server follow Readme.md docs

**Comment by codito** [comment]
@yiyanwannian thanks, I will update readme.md. Can you please try `docfx.exe` from this link (https://github.com/dotnet/docfx/releases/download/v2.15.3/docfx.zip)?

**Comment by pvlakshm** [comment]
Closing this. Reactivate if need be.

**Comment by yiyanwannian** [comment]
Thanks
