### ISSUE TITLE
Is this doc online?

### ISSUE THREAD

**Issue by GuardRex** [Microsoft/vstest-docs#43]
RE: https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md

> You've found the GitHub repository which contains the content for the Visual Studio Test Platform documentation.

Is the "Visual Studio Test Platform documentation" built and online? If yes, is the *TestCase filter* doc hosted online as a webpage within a web-based document set ... I can't find it hosted anywhere in a website, or is it only hosted on GH at that link?

cc/ @smadala @codito

**Comment by codito** [comment]
@GuardRex the docs are not hosted online (yet). We plan to fix that in near future (/cc @pvlakshm).
