### ISSUE TITLE
Coverage in .net core 1.1 is not working

### ISSUE THREAD

**Issue by rochydevs** [Microsoft/vstest-docs#55]
Hi,

I’m trying to get the test coverage from a dotnet core test project but I can’t see the results (the tests runs successfully). I followed the steps that you shared on  https://github.com/Microsoft/vstest/issues/579.

I you can take a look on my test solution i will apreciate it, you can download from this url https://www.dropbox.com/s/qjsqdxtckmauvtt/TestSolution.zip?dl=0

Included a base test, a nunit test project and xunit test project, when runs coverage process the result are from test ptojects not for the base project.

Thanks in advance,

Roger

**Comment by rochydevs** [comment]
My apologize,  I added this tag "<DebugType>Full</DebugType>" in the test projects but not in the base project, now it’s working!

**Comment by codito** [comment]
Clarified with 06f9dc0 . Thanks for reporting the issue.
