### ISSUE TITLE
Unable to see Code Coverage Results from VS 2017

### ISSUE THREAD

**Issue by SrivatsaMarichi** [Microsoft/vstest-docs#56]
Hi Team,

I have added the package for Code Coverage from the Package Manager Console by passing **Install-Package Microsoft.CodeCoverage -Version 1.0.3**.

I then ran **Analyze Code Coverage** but I don't see any results in **Code Coverage Results** window. 

I am trying this for **.NetCoreApp 1.0,** Can anyone help me out here?

**Visual Studio Enterprise 2017 Version- 15.2(26430.6)**

Also I want to know is there a support for the same on VSTS CI builds? If so, how?

Thanks,
Srivatsa

**Comment by codito** [comment]
Moved to vstest#909.
